import { __UtilsMethods2__ } from './utils';
import { initLogger } from '../wasm/iota_sdk_wasm';
declare const createClient: (...args: any[]) => any;
declare const createWallet: (...args: any[]) => any;
declare const createSecretManager: (...args: any[]) => any;
declare const callClientMethodAsync: (...args: any[]) => any;
declare const callSecretManagerMethodAsync: (...args: any[]) => any;
declare const callUtilsMethod: (...args: any[]) => any;
declare const callWalletMethodAsync: (...args: any[]) => any;
declare const listenWalletAsync: (...args: any[]) => any;
declare const destroyWallet: (...args: any[]) => any;
declare const destroyClient: (...args: any[]) => any;
declare const getClientFromWallet: (...args: any[]) => any;
declare const getSecretManagerFromWallet: (...args: any[]) => any;
declare const listenMqtt: (...args: any[]) => any;
declare const migrateStrongholdSnapshotV2ToV3: (...args: any[]) => any;
declare const migrateDbChrysalisToStardust: (...args: any[]) => any;
declare const callUtilsMethod2: (method: __UtilsMethods2__) => any;
export { initLogger, createClient, createWallet, createSecretManager, callClientMethodAsync, callSecretManagerMethodAsync, callUtilsMethod, callUtilsMethod2, callWalletMethodAsync, listenWalletAsync, destroyWallet, destroyClient, getClientFromWallet, getSecretManagerFromWallet, listenMqtt, migrateStrongholdSnapshotV2ToV3, migrateDbChrysalisToStardust, };
